export const PRICING = {
    observer: {
        name: 'Observer',
        priceLabel: 'Free',
        cadenceLabel: 'Forever',
        tagline: 'See what the product actually does.',
        subline: 'No card required. Start with the interactive sample dossier, then run your first full analysis when you’re ready.',
        ctaLabel: 'Start Free',
        ctaHref: '/ingest',
        whoItsFor: 'For the practitioner who needs to see the machinery before they trust it.',
        features: [
            'Interactive sample dossier (precomputed)',
            '1 full analysis (lifetime)',
            'Full structured dossier workflow',
            'Primary mechanic read + Recommended Move',
            'Trigger distribution map',
            'Persuasion density score',
            'Private Vault (limited)',
        ],
    },
    strategic: {
        name: 'Strategic',
        monthlyPrice: 99,
        yearlyPrice: 990,
        monthlyLabel: '$99 / month',
        yearlyLabel: '$990 / year',
        savingsLabel: 'Save 20%',
        tagline: 'For practitioners who use it every week.',
        subline: 'One seat. 250 analyses each cycle. Everything you need to work faster and present stronger.',
        ctaLabel: 'Start Strategic',
        whoItsFor: 'The high-volume operator. The strategist who is in the room every week and needs a clinical edge.',
        checkoutPlanKey: 'strategic',
        features: [
            '250 analyses each cycle',
            'Full Intelligence Vault access',
            'Differential Diagnosis for route comparison',
            'Clone Engine',
            'Blueprint Tab',
            'Audience Tab',
            'White-label dossier export',
            'Embed widget',
            'Boards (personal strategic workspace)',
            'Priority analysis queue',
        ],
    },
    professional: {
        name: 'Professional',
        monthlyPrice: 249,
        yearlyPrice: 2490,
        monthlyLabel: '$249 / month',
        yearlyLabel: '$2490 / year',
        savingsLabel: 'Save 16%',
        tagline: 'For strategists who present to clients and teams.',
        subline: '3-5 seats. Shared intelligence. Every tool you need to build client-ready outcomes.',
        ctaLabel: 'Start Professional',
        whoItsFor: 'The strategy team. For groups that need to align fast and move work without the subjective feedback loops.',
        checkoutPlanKey: 'professional',
        features: [
            'All Strategic features',
            '3-5 team seats',
            'Shared Intelligence Vault',
            'Shared Boards',
            'Shared decision artifacts',
            'Team & Seats management',
            'Priority support',
        ],
    },
    agency: {
        name: 'Agency Sovereignty',
        monthlyLabel: 'From $1,000 / month',
        cadenceLabel: 'Annual contract',
        tagline: 'For agencies that run intelligence as a service.',
        subline: 'It’s billable intelligence infrastructure your agency presents to clients as your own.',
        ctaLabel: 'Book Agency Demo',
        ctaHref: 'mailto:hello@visualdecompiler.com?subject=Agency%20Sovereignty%20Demo',
        contactLabel: 'Or start a conversation — hello@visualdecompiler.com',
        whoItsFor: 'The Elite Agency. For teams that need a shared competitive intelligence layer they can bill back to clients as premium strategic IP.',
        features: [
            'Up to 10 team seats',
            'Shared Intelligence Vault',
            'Sovereign Boards',
            'Agency Settings',
            'Full white-label infrastructure',
            'Team & Seats management',
            'Resend-powered team invite emails',
            'Priority support',
            'Dedicated onboarding session',
            'Usage reporting & team analytics',
        ],
        positioningQuote: 'A single pitch win at Agency level covers the annual cost. A single white-label dossier presented to a client covers a month.',
    },
} as const;

export const PRICING_COMPARISON_ROWS = [
    ['Forensic Quality Score', 'Core', 'Full Stack', 'Full Stack', 'Sovereign'],
    ['Mechanic Extraction Depth', 'Core', 'Deep Read', 'Deep Read', 'Sovereign'],
    ['Execution DNA Detail', 'Core', 'Deep Scan', 'Deep Scan', 'Sovereign'],
    ['Stress Test Modules', '—', 'Core', 'Expanded', 'Sovereign'],
    ['Constraint Mapping', '—', 'Core', 'Expanded', 'Sovereign'],
    ['Comparative Diagnostics (A/B)', '—', 'Included', 'Included', 'Sovereign'],
    ['Market Pulse Context', '—', 'Snapshot', 'Included', 'Sovereign'],
    ['Dossier Export Depth', 'Standard', 'Client-ready', 'Client-ready', 'Agency-grade'],
    ['Team Collaboration', 'Solo', 'Solo', 'Shared', 'Infrastructure layer'],
    ['White-label / Agency Delivery', '—', 'Export only', 'Shared delivery', 'Total Sovereignty'],
] as const;

export const PRICING_POSITIONING_LINES = [
    'AI chat can critique an ad once. Visual Decompiler turns the read into a structured workflow your team can reuse.',
    'Each tier increases the depth of the artifact: dossier quality, vault memory, comparison, collaboration, and delivery.',
    'You are not just buying more analyses. You are buying a clearer path from asset to evidence to decision.',
] as const;
