export const PRICING = {
    observer: {
        name: 'Observer',
        priceLabel: 'Free',
        cadenceLabel: 'Forever',
        tagline: 'See what the product actually does.',
        subline: 'No card required. No time limit. Five complete analyses, not a watered-down preview.',
        ctaLabel: 'Start Decompiling Free',
        ctaHref: '/ingest',
        whoItsFor: 'For practitioners who want to see real output before committing.',
        features: [
            '5 full analyses per month',
            'All five intelligence surfaces',
            'Primary mechanic read + Recommended Move',
            'Trigger distribution map',
            'Persuasion density score',
            'Intelligence Vault (read-only, your 5 analyses)',
            'Standard export (PDF dossier)',
        ],
    },
    strategic: {
        name: 'Strategic Unit',
        monthlyPrice: 99,
        yearlyPrice: 990,
        monthlyLabel: '$99 / month',
        yearlyLabel: '$990 / year',
        savingsLabel: 'Save 20%',
        tagline: 'For practitioners who use it every week.',
        subline: 'One seat. Unlimited analyses. Everything you need to work faster and present stronger.',
        ctaLabel: 'Start Strategic Unit',
        trialLabel: '14-day free trial included',
        whoItsFor: 'Art Directors, Creative Directors, Copywriters, and Brand Managers who need analysis on demand — not five times a month.',
        checkoutPriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY || 'price_1T64QL0LZZUO4xz44Cwvqdzk',
        features: [
            'Unlimited analyses',
            'Full Intelligence Vault access',
            'Differential Diagnosis',
            'Clone Engine',
            'Blueprint Tab',
            'Audience Tab',
            'White-label dossier export',
            'Embed widget',
            'Boards (personal strategic workspace)',
            'Priority analysis queue',
        ],
    },
    professional: {
        name: 'Professional',
        monthlyPrice: 249,
        yearlyPrice: 2490,
        monthlyLabel: '$249 / month',
        yearlyLabel: '$2490 / year',
        savingsLabel: 'Save 16%',
        tagline: 'For strategists who present to clients and teams.',
        subline: '3-5 seats. Shared intelligence. Every tool you need to build client-ready outcomes.',
        ctaLabel: 'Start Professional',
        trialLabel: '14-day free trial included',
        whoItsFor: 'Small creative studios and in-house strategy teams (2-5 people) who need collaboration features.',
        checkoutPriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_PROFESSIONAL_MONTHLY || 'price_professional_placeholder',
        features: [
            'All Strategic Unit features',
            '3-5 team seats',
            'Shared Intelligence Vault',
            'Shared Boards',
            'Team & Seats management',
            'Priority support',
        ],
    },
    agency: {
        name: 'Agency Sovereignty',
        monthlyLabel: 'From $1,000 / month',
        cadenceLabel: 'Annual contract',
        tagline: 'For agencies that run intelligence as a service.',
        subline: 'It’s billable intelligence infrastructure your agency presents to clients as your own.',
        ctaLabel: 'Book a Demo',
        ctaHref: 'mailto:hello@visualdecompiler.com?subject=Agency%20Sovereignty%20Demo',
        contactLabel: 'Or start a conversation — hello@visualdecompiler.com',
        whoItsFor: 'Agency strategy teams, new business leads, and creative directors who need a shared competitive intelligence layer they can bill back to clients as premium strategic IP.',
        features: [
            'Up to 10 team seats',
            'Shared Intelligence Vault',
            'Sovereign Boards',
            'Agency Settings',
            'Full white-label infrastructure',
            'Team & Seats management',
            'Resend-powered team invite emails',
            'Priority support',
            'Dedicated onboarding session',
            'Usage reporting & team analytics',
        ],
        positioningQuote: 'A single pitch win at Agency level covers the annual cost. A single white-label dossier presented to a client covers a month.',
    },
} as const;

export const PRICING_COMPARISON_ROWS = [
    ['Analyses per month', '5', 'Unlimited', 'Unlimited', 'Unlimited'],
    ['Intelligence surfaces (all 5)', '✦', '✦', '✦', '✦'],
    ['Recommended Move', '✦', '✦', '✦', '✦'],
    ['Differential Diagnosis', '—', '✦', '✦', '✦'],
    ['Clone Engine', '—', '✦', '✦', '✦'],
    ['Blueprint Tab', '—', '✦', '✦', '✦'],
    ['Audience Tab', '—', '✦', '✦', '✦'],
    ['Intelligence Vault', 'Read', 'Full', 'Shared', 'Shared'],
    ['White-label export', '—', '✦', '✦', '✦'],
    ['Embed widget', '—', '✦', '✦', '✦'],
    ['Boards', '—', 'Personal', 'Shared', 'Shared'],
    ['Team seats', '1', '1', '3-5', 'Up to 10'],
    ['Agency branding & dossier identity', '—', '—', '—', '✦'],
    ['Team & Seats management', '—', '—', '✦', '✦'],
    ['Usage reporting', '—', '—', '—', '✦'],
    ['Dedicated onboarding', '—', '—', '—', '✦'],
    ['Priority support', '—', '—', '✦', '✦'],
] as const;

export const PRICING_POSITIONING_LINES = [
    'Ad libraries show you what ads exist.',
    'Social intelligence platforms show you what people say about brands.',
    'Visual Decompiler tells you why the ad is working — and how to use that in the room.',
] as const;
