import { supabaseAdmin } from '@/lib/supabase';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';

export const dynamic = 'force-dynamic';

export default async function BoardsPage() {
    // Attempt to pull boards. If the table doesn't exist or is empty, it will return [] gracefully.
    const { data: boards } = await supabaseAdmin.from('boards').select('*').order('created_at', { ascending: false }).limit(20);

    const safeBoards = boards || [];

    return (
        <div className="min-h-screen bg-black text-white p-8 md:p-12">
            <header className="mb-16">
                <h1 className="text-3xl lg:text-5xl font-sans tracking-tighter uppercase whitespace-nowrap overflow-hidden text-ellipsis">
                    Sovereign Boards
                </h1>
                <p className="mt-4 text-neutral-500 font-mono text-xs tracking-widest uppercase">
                    Curated Client Intelligence & Forensic Collections
                </p>
            </header>

            {safeBoards.length === 0 ? (
                <div className="w-full aspect-video border-[1px] border-dashed border-neutral-800 flex items-center justify-center">
                    <span className="text-neutral-500 font-mono text-sm tracking-widest uppercase text-center max-w-md px-4 leading-relaxed">
                        NO BOARDS FOUND.<br /><br />
                        FORENSIC COLLECTIONS WILL APPEAR HERE ONCE GENERATED BY THE OS.
                    </span>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {safeBoards.map((board: any) => (
                        <Link
                            key={board.id}
                            href={`/boards/${board.id}`}
                            className="group block relative aspect-[4/3] bg-[#0A0A0A] border border-neutral-900 overflow-hidden hover:border-white transition-colors duration-500"
                        >
                            <div className="absolute inset-0 flex flex-col justify-end p-6">
                                <h3 className="text-lg font-bold tracking-widest uppercase text-white mb-2">
                                    {board.name || 'Untitled Board'}
                                </h3>
                                <p className="text-[10px] text-neutral-500 font-mono tracking-widest uppercase">
                                    {new Date(board.created_at).toLocaleDateString()}
                                </p>
                            </div>

                            <div className="absolute top-6 right-6 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                                <ArrowUpRight className="w-5 h-5 text-white" />
                            </div>
                        </Link>
                    ))}
                </div>
            )}
        </div>
    );
}
